git-commitas: Improve error messages

diff --git a/Scripts/git-commitas b/Scripts/git-commitas
--- a/Scripts/git-commitas
+++ b/Scripts/git-commitas
@@ -2,10 +2,14 @@
 
 # Use shellcheck to lint
 
+# Return codes:
+# * 1: Missing or invalid argument or data
+# * 2: External tool error
+
 USAGE="$(cat << END
 Usage: git commitas <as-user> <arguments>
-       git commitas --help | -h
-       git commitas --man
+       git commitas -h | --help
+       git commitas --man | --manual
 END
 )"
 
@@ -38,7 +42,7 @@ shift
 
 if [ -z "$useras" ]
 then
-	echo "Error: missing user name" >&2
+	echo "Error: missing as-user" >&2
 	echo "$USAGE" >&2
 	exit 1
 fi
@@ -48,13 +52,14 @@ if [ "$useras" = '--help' ] || [ "$useras" = '-h' ]
 then
 	echo "$USAGE"
 	exit 0
-elif [ "$useras" = '--man' ]
+elif [ "$useras" = '--man' ] || [ "$useras" = '--manual' ]
 then
 	echo "$MAN"
 	exit 0
 elif [ "$(echo "$useras" | cut -c1)" = '-' ] # First character is '-'
 then
 	echo "Error: unknown flag '$useras'" >&2
+    echo "$USAGE" >&2
 	exit 1
 fi
 
@@ -63,26 +68,44 @@ fi
 invalid="$(echo "$useras" | tr -d '\n\000')"
 if [ "$useras" != "$invalid" ] # Some characters were stripped
 then
-	echo "Error: invalid user-as" >&2
+	echo "Error: invalid as-user '$useras'. Newlines and null characters aren't allowed." >&2
 	exit 1
 fi
 
 # Query git config
 name="$(git config --get "users.$useras.name")"
-if [ $? -eq 1 ]
-then
-	echo "Error: could not find 'users.$useras.name'" >&2
-	exit 1
+ret=$?
+namemissing="$([ $ret -eq 1 ] && echo "1")"
+if [ $ret -gt 1 ]
+	then echo "git errored with return code $ret while querying config." >&2
+	exit 2
 fi
 
 email="$(git config --get "users.$useras.email")"
-if [ $? -eq 1 ]
-then
-	echo "Error: could not find 'users.$useras.email'" >&2
-	exit 1
+ret=$?
+emailmissing="$([ $ret -eq 1 ] && echo "1")"
+if [ $? -gt 1 ]
+	then echo "git errored with return code $ret while querying config." >&2
+	exit 2
 fi
 
-echo "git-commitas: committing as \"$name\" <$email>"
+# Handle errors in a more user-friendly way
+if [ "$namemissing" ] && [ "$emailmissing" ]
+then
+	echo "Missing section [users \"$useras\"] in git config. Did you forget to add it?" >&2
+elif [ "$namemissing" ]
+then
+	echo "Missing 'name' field under section [users \"$useras\"] in git config. Did you forget to add it?" >&2
+elif [ "$emailmissing" ]
+then
+	echo "Missing 'email' field under section [users \"$useras\"] in git config. Did you forget to add it?" >&2
+fi
+if [ "$namemissing" ] || [ "$emailmissing" ]
+then
+	exit 2
+fi
+
+echo "Committing as \"$name\" <$email>."
 
 exec env "GIT_AUTHOR_NAME=$name" "GIT_AUTHOR_EMAIL=$email" \
 	"GIT_COMMITTER_NAME=$name" "GIT_COMMITTER_EMAIL=$email" \
